apiVersion: v1
kind: Pod

metadata:
  name: my-pod
  labels:
    project: calculator

spec:
  containers:
    - name: calculator
      image: calculator-new
      imagePullPolicy: Never
      ports:
        - containerPort: 5000